export default function PilotProgrammeManchester() {
  return (
    <article>
      <p>
        Every technology that eventually becomes infrastructure passes through a moment where real
        businesses, in a real geography, test it under real conditions. For ADN-1, that moment is the
        Independent Retail Pilot, running through 2026. Five independent retailers across Greater Manchester
        have signed Letters of Intent. The pilot is not framed as a proof of concept for the hardware alone.
        It is a proof of doctrine, establishing whether Economic Sterilisation deployed at
        street level produces measurable behavioural change in a concentrated urban area.
      </p>

      {/* Featured Image */}
      <div style={{ margin: "40px 0" }}>
        <img
          src="https://images.unsplash.com/photo-1543269664-56d93c1b41a6?w=1200&q=80"
          alt="Manchester city"
          style={{ width: "100%", maxHeight: 400, objectFit: "cover", borderRadius: 4, display: "block", marginBottom: 8 }}
        />
        <p style={{ fontFamily: "monospace", fontSize: 11, color: "#8A7560", margin: 0 }}>Photo: Unsplash</p>
      </div>

      <h2>Why Greater Manchester</h2>

      <p>
        Greater Manchester is one of the UK's most significant concentrations of independent retail
        outside London. The city's commercial geography includes dense high streets, community retail
        corridors, and mixed-use neighbourhoods where independent grocers, jewellers, and convenience
        operators sit alongside national chains. It is also a region that consistently ranks among UK
        cities with elevated organised retail crime activity. Greater Manchester Police have documented
        the pressure on independent retailers repeatedly, and the ACS Crime Report 2024 figures reflect
        a national pattern that the region exemplifies: convenience stores losing an average of GBP
        4,600 per year to theft, before accounting for the harder-to-quantify costs of staff anxiety,
        insurance adjustment, and operational disruption.
      </p>
      <p>
        The geography also matters for the network effect. Economic sterilisation achieves its maximum
        deterrent power when multiple stores in a shared catchment carry the "Protected by Mykei
        Securities" decal. A thief operating in Moston or Prestwich who encounters a marked store cannot
        simply move to the adjacent premises if that premises is also marked. The pilot concentrates
        five stores across a single metropolitan area deliberately, to begin generating that adjacency
        effect from day one.
      </p>

      <h2>The Five Pilot Partners</h2>

      <p>
        The businesses that have signed Letters of Intent represent a cross-section of independent
        retail in Greater Manchester. Cashoppers Jewellers operates in the jewellery and high-value
        goods sector. Shop9jaLtd is a community grocery retailer. Khawaja Food Store serves the
        convenience and food market. Moston Lane Poundstore is a value retail operator on one of the
        district's busiest commercial streets. Go Local Bobby's in Prestwich is a community convenience
        store serving a dense residential catchment.
      </p>
      <p>
        These are not corporate test accounts. They are owner-operated businesses absorbing real losses
        every week, making decisions about security spend with limited capital and no dedicated security
        function. Their participation is significant precisely because the economics have to work for
        operators like them. If ADN-1 cannot demonstrate value to a convenience retailer on Moston Lane,
        it cannot claim to solve the problem it was built to address.
      </p>

      <h2>What the Pilot Includes and What It Does Not</h2>

      <p>
        Each pilot partner receives a physical ADN-1 unit installed on their highest-risk shelf
        position, identified during onboarding through a brief assessment of their store layout and
        theft history. They receive the "Protected by Mykei Securities" window decal, positioned at
        the entrance or on the primary shopfront glazing. They receive direct onboarding with the
        founder and a direct communication channel with Michael Esema throughout the pilot period.
        Their store is registered in the Mykei Registry, so any forensic reference code
        generated by their unit is linked to their location and item categories from the first
        activation.
      </p>
      <p>
        What the pilot does not include matters equally. There is no CCTV component. There are no
        biometric systems. There is no staff training programme. There is no operational change
        required. The unit operates autonomously. Staff continue their normal routines. The only
        addition to the store environment is the hardware, the decal, and the knowledge that every
        activation is logged and registered.
      </p>
      <p>
        Mykei collects event logs from each unit: sweep count, deployment count, and timestamp. These
        logs are anonymised and do not capture personal data. They serve two functions: providing
        retailers with a record of activation events, and generating the aggregate dataset that will
        inform product refinement ahead of wider rollout. At the close of the pilot, partners will
        receive a summary of their event data and options for continued subscription. Feedback from
        the pilot period will directly shape the product before it scales beyond Greater Manchester.
      </p>
      <p>
        Retailers carrying average theft losses of GBP 4,600 per year have clear economic justification
        for participation. Founders pricing is available. Apply at mykei.io/pilot.
      </p>
    </article>
  );
}
